services:
  - type: static
    name: hospital-care-admin
    runtime: node
    repo: https://github.com/akankshathakur7253-gif/hospital-care-admin.git
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dr-backend-evhe.onrender.com/api
