services:
  - type: web
    name: hospital-care-admin
    runtime: static
    repo: https://github.com/SVIGHNESH/DRAPP_ADMIN_PANEL.git
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dr-backend-evhe.onrender.com/api
